import {
  Activity,
  BellDot,
  BellRing,
  CircleGauge,
  CircleStop,
  Droplets,
  Gauge,
  LayoutDashboard,
  Lock,
  MonitorDot,
  Play,
  PlayCircle,
  Plus,
  Power,
  PowerOff,
  RefreshCw,
  RotateCw,
  ScanLine,
  ShieldAlert,
  Sigma,
  SlidersHorizontal,
  Square,
  ToggleLeft,
  Trash2,
  TrendingUp,
  Unlock,
  Waves,
  Wind,
  X,
  Zap,
} from "lucide-react";

const iconMap = {
  activity: Activity,
  "bell-dot": BellDot,
  "bell-ring": BellRing,
  "circle-gauge": CircleGauge,
  "circle-stop": CircleStop,
  droplets: Droplets,
  gauge: Gauge,
  "layout-dashboard": LayoutDashboard,
  lock: Lock,
  "monitor-dot": MonitorDot,
  play: Play,
  "play-circle": PlayCircle,
  plus: Plus,
  power: Power,
  "power-off": PowerOff,
  "refresh-cw": RefreshCw,
  "rotate-cw": RotateCw,
  "scan-line": ScanLine,
  "shield-alert": ShieldAlert,
  sigma: Sigma,
  "sliders-horizontal": SlidersHorizontal,
  square: Square,
  "toggle-left": ToggleLeft,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  unlock: Unlock,
  waves: Waves,
  wind: Wind,
  x: X,
  zap: Zap,
};

export default function Icon({ name, ...props }) {
  const IconComponent = iconMap[name] || LayoutDashboard;
  return <IconComponent aria-hidden="true" {...props} />;
}
